import React, { Suspense, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import Lenis from 'lenis';
import { FiArrowUpRight, FiGithub, FiLinkedin, FiMenu, FiMoon, FiPhone, FiSend, FiSun, FiX } from 'react-icons/fi';
import './style.css';

const dimensions = [['01', 'About', 'The mind behind the multiverse.', 'cyan', 'K'], ['02', 'Technology Core', 'Every technology is a new universe to explore.', 'green', '</>'], ['03', 'Projects', 'Artifacts waiting to be revealed.', 'gold', '◎'], ['04', 'Learning', 'No final level. Only the next horizon.', 'violet', '∞'], ['05', 'Contact', 'An open portal for exceptional ideas.', 'amber', '↗']];
const currentSkills = ['HTML', 'CSS', 'JavaScript', 'React', 'Tailwind CSS', 'Three.js', 'GSAP', 'Git', 'GitHub', 'C', 'SQL'];
const futureSkills = ['Node.js', 'Express.js', 'MongoDB', 'Next.js', 'TypeScript'];
const timeline = ['Started Programming', 'C Language', 'HTML', 'CSS', 'JavaScript', 'React', 'Tailwind CSS', 'Three.js', 'GSAP', 'Future Full Stack Engineer'];
const projects = [
  ['Emotion Recognition Audio', 'A Python project focused on identifying emotion from audio signals.', 'Python', 'https://github.com/CodeInTheHorizon/Emotion_Recognition_Audio'],
  ['Predictive Customer Churn XAI', 'A customer churn prediction project with explainable insights.', 'Python · XAI', 'https://github.com/CodeInTheHorizon/predictive-customer-churn-xai'],
  ['LSTM MS Stock', 'A time-series stock prediction experiment using LSTM networks.', 'Python · LSTM', 'https://github.com/CodeInTheHorizon/LSTM_MS_STOCK'],
  ['2 Leaves And A Bud Clone', 'A frontend recreation project inspired by a polished product experience.', 'Frontend', 'https://github.com/CodeInTheHorizon/2leavesAndABud_clone']
];
const PortalScene = React.lazy(() => import('./PortalScene.jsx'));

function Nav({ light, setLight }) { const [open, setOpen] = useState(false); const close = () => setOpen(false); return <nav><a className="logo" href="#home" onClick={close}>K<span>·</span></a><div className={`nav-links ${open ? 'is-open' : ''}`}><a href="#about" onClick={close}>About</a><a href="#skills" onClick={close}>Skills</a><a href="#work" onClick={close}>Projects</a><a href="#journey" onClick={close}>Learning</a><a href="#contact" onClick={close}>Contact</a></div><div className="nav-actions"><button aria-label="Switch theme" className="theme" onClick={() => setLight(!light)}>{light ? <FiMoon /> : <FiSun />}</button><button aria-label="Open navigation" className="menu" onClick={() => setOpen(!open)}>{open ? <FiX /> : <FiMenu />}</button></div></nav> }
function Dimension({ item, i }) { return <motion.a href={`#${['about', 'skills', 'work', 'journey', 'contact'][i]}`} className={`world ${item[3]}`} initial={{ opacity: 0, y: 48 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .25 }} transition={{ duration: .7, delay: i * .06 }}><div className="world-orb">{item[4]}</div><div><span>{item[0]} / DIMENSION</span><h3>{item[1]}</h3><p>{item[2]}</p></div><FiArrowUpRight className="world-arrow" /></motion.a> }
function SkillGroup({ label, list }) { return <div className="skill-group"><p className="eyebrow">{label}</p><div className="skill-cloud">{list.map(skill => <span key={skill}>{skill}</span>)}</div></div> }

function App() {
  const [light, setLight] = useState(false); const [entered, setEntered] = useState(false); const cursor = useRef();
  useEffect(() => { const lenis = new Lenis({ lerp: .09 }); let id; const raf = time => { lenis.raf(time); id = requestAnimationFrame(raf) }; id = requestAnimationFrame(raf); const move = event => { if (cursor.current) cursor.current.style.transform = `translate(${event.clientX}px,${event.clientY}px)` }; window.addEventListener('pointermove', move); return () => { cancelAnimationFrame(id); lenis.destroy(); window.removeEventListener('pointermove', move) } }, []);
  const enter = () => { setEntered(true); document.querySelector('#dimensions').scrollIntoView({ behavior: 'smooth' }) };
  return <main className={light ? 'light' : ''}><div className="cursor" ref={cursor} aria-hidden="true" /><Nav light={light} setLight={setLight} />
    <section id="home" className="hero"><div className="hero-copy"><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .2 }} className="eyebrow">CSE STUDENT · FRONTEND DEVELOPER · CONTINUOUS LEARNER <i /></motion.p><motion.h1 initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}>KSHITIJ<br /><em>KUMAR SONI</em></motion.h1><motion.p className="lede" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .5 }}>I don't just build websites. I build immersive digital experiences that combine modern frontend engineering, creative motion design and intuitive user experiences.<br /><br />Currently mastering Frontend Development while evolving into a Full Stack Engineer.</motion.p><button className="enter" onClick={enter}>Enter the multiverse <FiArrowUpRight /></button></div><div className="portal"><Suspense fallback={null}><PortalScene light={light} /></Suspense><p className="portal-label">GWALIOR / INDIA · UNIVERSE 001</p></div><div className="scroll">SCROLL TO TRAVEL <span /></div></section>
    <section id="dimensions" className="section universes"><p className="eyebrow">FIVE DIMENSIONS / ONE EXPLORER</p><h2>Choose a <em>dimension.</em></h2><p className="intro">A cinematic map of the places where curiosity turns into craft.</p><div className="world-grid">{dimensions.map((item, i) => <Dimension key={item[0]} item={item} i={i} />)}</div></section>
    <section id="about" className="section story"><div className="story-number">K / ∞</div><div><p className="eyebrow">THE MIND BEHIND THE MULTIVERSE</p><h2>Ideas become alive<br />through <em>motion.</em></h2><p>I am a Computer Science Engineering student at MITS, Gwalior, who enjoys transforming ideas into interactive digital experiences. Instead of creating ordinary websites, I focus on interfaces that feel alive through animation, motion and thoughtful user experience.</p><p>Every project teaches me something new. Learning is not a phase—it is a lifelong journey.</p><div className="highlights">{['CSE Student', 'Creative Frontend Developer', 'Continuous Learner', 'Problem Solver', 'Future Full Stack Engineer'].map(x => <span key={x}>{x}</span>)}</div></div></section>
    <section id="skills" className="section skills"><p className="eyebrow">TECHNOLOGY CORE</p><h2>Every technology becomes<br />another <em>universe.</em></h2><p className="intro">Tools I use to engineer immersive digital experiences.</p><SkillGroup label="CURRENTLY EXPLORING" list={currentSkills} /><SkillGroup label="CURRENTLY LEARNING" list={futureSkills} /></section>
    <section id="work" className="section work"><p className="eyebrow">UNIVERSES I’VE BUILT</p><h2>Artifacts returned from <em>the void.</em></h2><p className="intro">Open any artifact to explore its source code on GitHub.</p><div className="projects">{projects.map((project, i) => <motion.a href={project[3]} target="_blank" rel="noreferrer" className="project project-link" key={project[0]} whileHover={{ y: -9 }}><div className={`artifact a${i % 3}`}><span>✦</span></div><div className="project-meta"><span>0{i + 1} / GITHUB</span><FiArrowUpRight /></div><h3>{project[0]}</h3><p>{project[1]}</p><small>{project[2]}</small></motion.a>)}</div></section>
    <section id="journey" className="section journey"><p className="eyebrow">INFINITE LEARNING TIMELINE</p><h2>No final level.<br />Only the next <em>horizon.</em></h2><p className="intro">Learning is the foundation of everything I build. Every technology mastered unlocks another universe.</p><div className="timeline">{timeline.map((step, i) => <motion.div initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .07 }} className="milestone" key={step}><b>{String(i + 1).padStart(2, '0')}</b><p>{step}</p></motion.div>)}</div></section>
    <section id="contact" className="contact"><div className="contact-ring"><div><p className="eyebrow">OPEN A PORTAL</p><h2>Let’s build something <em>extraordinary.</em></h2><p className="contact-copy">For collaborations, internships, freelance opportunities, or simply discussing creative ideas—my portal is always open.</p><a href="mailto:kshitijji30@gmail.com" className="enter">Send a signal <FiSend /></a><div className="contact-details"><a href="mailto:kshitijji30@gmail.com">kshitijji30@gmail.com</a><a href="tel:+919216798356"><FiPhone /> +91 9216798356</a><a aria-label="GitHub profile" href="https://github.com/CodeInTheHorizon" target="_blank" rel="noreferrer"><FiGithub /></a><a aria-label="LinkedIn profile" href="https://www.linkedin.com/in/codeinthehorizon/" target="_blank" rel="noreferrer"><FiLinkedin /></a></div></div></div></section><footer><span>DESIGNED & DEVELOPED BY KSHITIJ KUMAR SONI · © 2026</span><span>REACT · THREE.JS · TAILWIND CSS · GSAP</span></footer><AnimatePresence>{entered && <motion.div className="flash" initial={{ scale: 0, opacity: .9 }} animate={{ scale: 4, opacity: 0 }} transition={{ duration: .8 }} onAnimationComplete={() => setEntered(false)} />}</AnimatePresence>
  </main>
}
createRoot(document.getElementById('root')).render(<App />);
